# Generated by Django 2.2.10 on 2020-05-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='phones',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='phones',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='phones',
            name='release_date',
            field=models.DateField(max_length=100),
        ),
    ]
