# Generated by Django 2.2.10 on 2020-05-24 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phones',
            old_name='id',
            new_name='id_p',
        ),
    ]
