# Generated by Django 2.2.10 on 2020-05-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_auto_20200519_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='lte_exists',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='phones',
            name='slug',
            field=models.SlugField(),
        ),
    ]
